/** Optional browser / anti-bot escalation for Investigator page retrieval. */
import { assertSafeOutboundUrl } from "./ssrf-safe-fetch";
import { getAgenticExecutionScope } from "./agentic-execution-context";
import { logger } from "./logger";

export type BrowserFetchOptions = { scope?: string; signal?: AbortSignal };
const MAX_BROWSER_RESPONSE_BYTES = 2_000_000;
export function isChallengeHtml(html: string): boolean { if (!html || html.length < 40) return false; const head = html.slice(0, 8_000).toLowerCase(); return (/just a moment/.test(head) && /cloudflare/.test(head)) || /cf-browser-verification|cf-challenge|attention required!\s*\|\s*cloudflare/.test(head) || (/enable javascript and cookies to continue/.test(head) && html.length < 30_000) || /^HTTP 403/.test(html) || /^HTTP 503/.test(html); }
function maxBrowserFetches(): number { const n = Number(process.env.BROWSER_FETCH_MAX_PER_CASE ?? "5"); return Number.isFinite(n) && n > 0 ? Math.min(n, 20) : 5; }
function timeoutMs(): number { const n = Number(process.env.BROWSER_FETCH_TIMEOUT_MS ?? "25000"); return Number.isFinite(n) && n >= 5_000 ? Math.min(n, 60_000) : 25_000; }
const browserFetchCounts = new Map<string, number>();
export function resetBrowserFetchCount(scope?: string): void { if (scope) browserFetchCounts.delete(scope); else browserFetchCounts.clear(); }
export function getBrowserFetchCount(scope = "process"): number { return browserFetchCounts.get(scope) ?? 0; }
function throwIfAborted(signal?: AbortSignal): void { if (signal?.aborted) throw new Error("browser fetch cancelled"); }
function raceAbort<T>(promise: Promise<T>, signal?: AbortSignal): Promise<T> { if (!signal) return promise; return new Promise<T>((resolve, reject) => { const abort = () => reject(new Error("browser fetch cancelled")); if (signal.aborted) return abort(); signal.addEventListener("abort", abort, { once: true }); void promise.then((v) => { signal.removeEventListener("abort", abort); resolve(v); }, (e) => { signal.removeEventListener("abort", abort); reject(e); }); }); }
async function readResponseTextCapped(response: Response, signal?: AbortSignal): Promise<string> { throwIfAborted(signal); const declared = Number(response.headers.get("content-length") ?? NaN); if (Number.isFinite(declared) && declared > MAX_BROWSER_RESPONSE_BYTES) throw new Error(`browser response exceeds ${MAX_BROWSER_RESPONSE_BYTES} byte limit`); const reader = response.body?.getReader(); if (!reader) return (await response.text()).slice(0, MAX_BROWSER_RESPONSE_BYTES); const chunks: Uint8Array[] = []; let bytes = 0; try { for (;;) { throwIfAborted(signal); const part = await reader.read(); if (part.done) break; bytes += part.value.byteLength; if (bytes > MAX_BROWSER_RESPONSE_BYTES) { await reader.cancel().catch(() => undefined); throw new Error(`browser response exceeds ${MAX_BROWSER_RESPONSE_BYTES} byte limit`); } chunks.push(part.value); } } finally { reader.releaseLock(); } return new TextDecoder().decode(Buffer.concat(chunks.map((x) => Buffer.from(x)))); }
async function readJsonCapped<T>(response: Response, signal?: AbortSignal): Promise<T> { return JSON.parse(await readResponseTextCapped(response, signal)) as T; }
async function fetchViaScrapfly(url: string, signal?: AbortSignal): Promise<string | null> { const key = process.env.SCRAPFLY_API_KEY ?? ""; if (!key) return null; throwIfAborted(signal); try { const u = new URL("https://api.scrapfly.io/scrape"); u.searchParams.set("key", key); u.searchParams.set("url", url); u.searchParams.set("asp", "true"); u.searchParams.set("render_js", "true"); const resp = await fetch(u.toString(), { signal: signal ?? AbortSignal.timeout(timeoutMs()) }); if (!resp.ok) return null; const data = await readJsonCapped<{ result?: { content?: string } }>(resp, signal); const html = data?.result?.content ?? ""; return html.length > MAX_BROWSER_RESPONSE_BYTES ? null : html.length > 100 ? html : null; } catch (err: any) { if (signal?.aborted) throw new Error("browser fetch cancelled"); logger.debug({ err: err?.message, url }, "scrapfly fetch failed"); return null; } }
async function fetchViaZenRows(url: string, signal?: AbortSignal): Promise<string | null> { const key = process.env.ZENROWS_API_KEY ?? ""; if (!key) return null; throwIfAborted(signal); try { const u = new URL("https://api.zenrows.com/v1/"); u.searchParams.set("apikey", key); u.searchParams.set("url", url); u.searchParams.set("js_render", "true"); u.searchParams.set("premium_proxy", "true"); const resp = await fetch(u.toString(), { signal: signal ?? AbortSignal.timeout(timeoutMs()) }); if (!resp.ok) return null; const html = await readResponseTextCapped(resp, signal); return html.length > 100 ? html : null; } catch (err: any) { if (signal?.aborted) throw new Error("browser fetch cancelled"); logger.debug({ err: err?.message, url }, "zenrows fetch failed"); return null; } }
async function fetchViaBrowserlessContent(url: string, signal?: AbortSignal): Promise<string | null> { const token = process.env.BROWSERLESS_TOKEN ?? ""; if (!token) return null; throwIfAborted(signal); try { const endpoint = process.env.BROWSERLESS_CONTENT_URL ?? `https://production-sfo.browserless.io/content?token=${encodeURIComponent(token)}`; const resp = await fetch(endpoint, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ url, gotoOptions: { waitUntil: "domcontentloaded", timeout: timeoutMs() } }), signal: signal ?? AbortSignal.timeout(timeoutMs() + 5_000) }); if (!resp.ok) return null; const html = await readResponseTextCapped(resp, signal); return html.length > 100 ? html : null; } catch (err: any) { if (signal?.aborted) throw new Error("browser fetch cancelled"); logger.debug({ err: err?.message, url }, "browserless content fetch failed"); return null; } }
async function fetchViaPlaywright(url: string, signal?: AbortSignal): Promise<string | null> { if (process.env.PLAYWRIGHT_ENABLED !== "1" && process.env.PLAYWRIGHT_ENABLED !== "true") return null; throwIfAborted(signal); try { const pw = await import("playwright").catch(() => null); if (!pw?.chromium) return null; const ws = process.env.PLAYWRIGHT_WS_ENDPOINT ?? ""; const browser = ws ? await pw.chromium.connectOverCDP(ws) : await pw.chromium.launch({ headless: true, args: ["--no-sandbox", "--disable-dev-shm-usage"] }); try { const page = (await browser.newPage()) as any; await page.route("**/*", async (route: any) => { try { await assertSafeOutboundUrl(route.request().url()); await route.continue(); } catch { await route.abort("blockedbyclient"); } }); await raceAbort(page.goto(url, { waitUntil: "domcontentloaded", timeout: timeoutMs() }), signal); throwIfAborted(signal); await raceAbort(page.waitForTimeout(2_500), signal).catch(() => undefined); throwIfAborted(signal); const html = await page.content(); return html.length > MAX_BROWSER_RESPONSE_BYTES ? null : html.length > 100 ? html : null; } finally { await browser.close().catch(() => undefined); } } catch (err: any) { if (signal?.aborted) throw new Error("browser fetch cancelled"); logger.debug({ err: err?.message, url }, "playwright fetch failed"); return null; } }
export async function browserFetchHtml(url: string, options: BrowserFetchOptions = {}): Promise<{ html: string; provider: string }> { throwIfAborted(options.signal); const scope = options.scope?.trim() || getAgenticExecutionScope(); const count = getBrowserFetchCount(scope); if (count >= maxBrowserFetches()) { logger.info({ url, scope, count }, "browser_fetch budget exhausted"); return { html: "", provider: "budget_exhausted" }; } browserFetchCounts.set(scope, count + 1); const attempts: Array<[string, () => Promise<string | null>]> = [["scrapfly", () => fetchViaScrapfly(url, options.signal)], ["zenrows", () => fetchViaZenRows(url, options.signal)], ["browserless", () => fetchViaBrowserlessContent(url, options.signal)], ["playwright", () => fetchViaPlaywright(url, options.signal)]]; for (const [provider, fn] of attempts) { throwIfAborted(options.signal); const html = await fn(); if (html && !isChallengeHtml(html)) { logger.info({ url, provider, bytes: html.length, scope }, "browser_fetch ok"); return { html, provider }; } if (html && isChallengeHtml(html)) logger.debug({ url, provider }, "browser_fetch still challenge HTML"); } logger.info({ url, scope }, "browser_fetch all providers failed or unconfigured"); return { html: "", provider: "none" }; }
export function browserFetchConfigured(): boolean { return Boolean(process.env.SCRAPFLY_API_KEY || process.env.ZENROWS_API_KEY || process.env.BROWSERLESS_TOKEN || process.env.PLAYWRIGHT_ENABLED === "1" || process.env.PLAYWRIGHT_ENABLED === "true"); }
