export type DiscoveryDimensionName="jurisdiction"|"sector"|"role"|"wealthMechanism"|"asset"|"sourceFamily"|"language";
export type DiscoveryDimension={name:DiscoveryDimensionName;observed:string[];hypotheses:string[];uncovered:string[]};
export type DiscoveryFrontierBranch={id:string;label:string;dimensions:Partial<Record<DiscoveryDimensionName,string>>;score:number;mode:"exploit"|"explore"|"blind_spot";rationale:string};
export type DiscoveryBridgeEntity={value:string;kind:"person"|"organization"|"asset_or_route";role:string|null;sourceCount:number;bridgeSignals:string[]};
export type DiscoveryIntelligence={version:1;dimensions:DiscoveryDimension[];frontier:DiscoveryFrontierBranch[];bridgeEntities:DiscoveryBridgeEntity[];negativeCoverage:string[];queryTransformFamilies:string[];sourceFamilySaturation:string[];explorationPolicy:{exploitation:number;structuredExploration:number;blindSpotExploration:number;reason:string}};
type Action={action:string;args:Record<string,unknown>;execution:string;urls:string[];findingNames?:string[];findingRoles?:string[];findings?:Array<{personName?:string|null;role?:string|null;value?:string}>};
const V:Record<DiscoveryDimensionName,string[]>={jurisdiction:["United States","United Kingdom","Canada","France","Germany","Italy","Spain","Norway","Sweden","Denmark","Finland","Netherlands","Poland","Slovenia","Croatia","Australia","New Zealand","Japan","South Korea","Singapore","United Arab Emirates"],sector:["casino","gaming","hotel","resort","hospitality","real estate","private equity","venture capital","family office","investment","technology","finance","banking","shipping","aviation","yacht","marina","energy","mining","construction","media","sports","luxury"],role:["owner","beneficial owner","shareholder","founder","co-founder","director","chairman","ceo","principal","managing partner","general partner","partner","investor","operator"],wealthMechanism:["company ownership","beneficial ownership","private equity","venture capital","family office","investment","real estate","asset ownership","licence","license","concession","holding company"],asset:["casino","hotel","resort","estate","property","aircraft","private jet","yacht","marina","company","investment fund","foundation","club"],sourceFamily:["registry","web_search","web_page","domain","osint"],language:["Slovenian","French","German","Italian","Spanish","Portuguese","Norwegian","Swedish","Danish","Finnish","Dutch","Polish","Japanese","Korean"]};
const L:Record<string,string>={Slovenia:"Slovenian",France:"French",Germany:"German",Italy:"Italian",Spain:"Spanish",Norway:"Norwegian",Sweden:"Swedish",Denmark:"Danish",Finland:"Finnish",Netherlands:"Dutch",Poland:"Polish",Japan:"Japanese","South Korea":"Korean"};
const norm=(x:string)=>x.toLowerCase().replace(/[^a-z0-9]+/g," ").trim(), uniq=(x:string[],n=12)=>[...new Set(x.filter(Boolean))].slice(0,n);
const family=(a:Action)=>a.action.includes("registry")?"registry":a.action.includes("search")?"web_search":a.action==="visit"||a.action==="browser_fetch"?"web_page":a.action.includes("domain")?"domain":a.action.includes("footprint")||a.action.includes("harvest")?"osint":"agent";
const branch=(label:string,d:Partial<Record<DiscoveryDimensionName,string>>,mode:DiscoveryFrontierBranch["mode"],score:number,rationale:string)=>({id:norm(label).slice(0,96),label,dimensions:d,score,mode,rationale});
export function buildDiscoveryIntelligence(input:{objective:string;facts?:Array<{claim:string}>;hypotheses?:Array<{label:string;entity:string;missingDiscriminators:string[]}>;negativeFindings?:string[];actions?:readonly Action[];repeatedSourceFamilies?:string[]}):DiscoveryIntelligence{
 const actions=[...(input.actions??[])], text=norm([input.objective,...(input.facts??[]).map(x=>x.claim),...(input.hypotheses??[]).flatMap(x=>[x.label,x.entity,...x.missingDiscriminators]),...actions.flatMap(x=>[String(x.args.query??""),String(x.args.hypothesis??""),String(x.args.purpose??""),...(x.findingNames??x.findings?.map(f=>String(f.personName??""))??[]),...(x.findingRoles??x.findings?.map(f=>String(f.role??""))??[])])].join(" "));
 const dimensions=Object.entries(V).map(([name,words])=>{const observed=words.filter(x=>text.includes(norm(x)));return{name:name as DiscoveryDimensionName,observed,hypotheses:[],uncovered:observed.length?[]:["dimension not yet resolved"]}});
 const by=Object.fromEntries(dimensions.map(x=>[x.name,x.observed])) as Record<DiscoveryDimensionName,string[]>, repeated=uniq(input.repeatedSourceFamilies??[]), frontier:DiscoveryFrontierBranch[]=[];
 const j=by.jurisdiction?.[0],s=by.sector?.[0],r=by.role?.[0],w=by.wealthMechanism?.[0],a=by.asset?.[0];
 if(j&&s)frontier.push(branch(j+" "+s+" ownership/control",{jurisdiction:j,sector:s,role:r??"owner / director / shareholder",wealthMechanism:w??"company ownership"},repeated.length?"explore":"exploit",repeated.length?.78:.86,"Core dimensions are visible; pursue attributable ownership/control while resisting saturation."));
 if(s)frontier.push(branch(s+" asset bridge",{sector:s,asset:a??s,role:"owner / operator / investor"},"explore",.72,"Use the business or asset as a bridge to people."));
 if(j)frontier.push(branch(j+" local-language discovery",{jurisdiction:j,language:L[j]??"local language",sourceFamily:"web_search"},"blind_spot",.62,"Test whether local-language sources expose hidden ownership or regulatory material."));
 if(r)frontier.push(branch(r+" terminology expansion",{role:r,sector:s??"objective sector",sourceFamily:"web_search"},"explore",.58,"Vary control terminology to avoid vocabulary lock-in."));
 const bridges=new Map<string,DiscoveryBridgeEntity>();
 for(const action of actions)for(const name of (action.findingNames??action.findings?.map(f=>String(f.personName??""))??[])){const key=norm(name);if(!key)continue;const old=bridges.get(key);if(old){old.sourceCount+=Math.max(1,action.urls.length);old.bridgeSignals=uniq([...old.bridgeSignals,...(action.findingRoles??action.findings?.map(f=>String(f.role??""))??[]).map(x=>"role:"+x)],8)}else bridges.set(key,{value:name,kind:"person",role:(action.findingRoles??action.findings?.map(f=>String(f.role??""))??[])[0]??null,sourceCount:Math.max(1,action.urls.length),bridgeSignals:(action.findingRoles??[]).map(x=>"role:"+x)})}
 const bridgeEntities=[...bridges.values()].sort((x,y)=>y.sourceCount+y.bridgeSignals.length-x.sourceCount-x.bridgeSignals.length).slice(0,8);
 if(bridgeEntities[0])frontier.push(branch("bridge through "+bridgeEntities[0].value,{role:bridgeEntities[0].role??"identified person",sourceFamily:"web_page"},"exploit",.75,"Observed candidate can open organization, ownership, asset, or contact branches."));
 const uncovered=dimensions.filter(x=>x.uncovered.length).map(x=>x.name);
 if(uncovered.length)frontier.push(branch("uncovered discovery dimensions",Object.fromEntries(uncovered.slice(0,4).map(x=>[x,"unknown"])) as Partial<Record<DiscoveryDimensionName,string>>,"blind_spot",.5,"Test unresolved dimensions before declaring the search space exhausted."));
 const families=new Set(by.sourceFamily??[]), structured=Math.max(.15,Math.min(.35,.2+repeated.length*.03)), blind=Math.max(.1,Math.min(.25,.1+uncovered.length*.08+repeated.length*.12));
 return{version:1,dimensions,frontier:frontier.sort((x,y)=>y.score-x.score).slice(0,8),bridgeEntities,negativeCoverage:uniq((input.negativeFindings??[]).slice(-12)),queryTransformFamilies:uniq([(by.role?.length?"leadership-role terminology":""),(by.wealthMechanism?.length?"ownership/control terminology":""),(by.asset?.length?"asset-to-person bridge terminology":"")],8),sourceFamilySaturation:repeated.length?repeated.map(x=>x+" repeated/saturated"):families.size>=3?["No major source-family saturation detected."]:["Source-family diversity is still shallow."],explorationPolicy:{exploitation:Math.max(.4,1-structured-blind),structuredExploration:structured,blindSpotExploration:blind,reason:"Advisory only: the Investigator still owns the next action."}};
}
export function renderDiscoveryIntelligence(value:DiscoveryIntelligence,maxChars=5000):string{
 const header="DISCOVERY FRONTIER (advisory search-space state; not a scripted route):",guidance="Treat frontier branches as hypotheses, not facts. The Investigator owns the next action. Prefer information gain, bridge entities, independent source families, and explicit negative tests.",body=JSON.stringify(value),budget=Math.max(1200,Math.min(8000,Math.floor(maxChars)));
 if((header+body+guidance).length<=budget)return[header,body,guidance].join("\n");
 const marker="[DISCOVERY FRONTIER BOUND: durable state remains outside prompt]",available=Math.max(200,budget-header.length-guidance.length-marker.length-8),head=Math.floor(available*.6);
 return[header,body.slice(0,head),marker,body.slice(-Math.max(1,available-head)),guidance].join("\n").slice(0,budget);
}