import { randomUUID } from "crypto";
import { withPermanentClient, permSadd, permSismember, permScard } from "./redis";
import { logger } from "./logger";
async function safeRedis<T>(fn:(rc:import("ioredis").Redis)=>Promise<T>,fallback:T):Promise<T>{return withPermanentClient(fn,fallback);}
export type JobStatus="queued"|"running"|"paused"|"done"|"failed"|"cancelled";
export interface JobState{jobId:string;type:string;status:JobStatus;progress:number;inserted:number;skipped:number;errors:number;total:number;startedAt:string;finishedAt?:string;message:string;atlasPhase?:number;atlasPhaseTotal?:number;entityProgress?:number;entityTotal?:number;entityNames?:string;atlasTelemetry?:string;outcome?:"complete"|"incomplete";resumable?:string;targetIds?:string;targetIndex?:number;targetTotal?:number;currentTargetId?:number;currentPhase?:string;completedTargetIds?:string;failedTargetIds?:string;retryCounts?:string;result?:string;}
export type AutoPipelineSchedulerStatus={enabled:boolean;active:boolean;activatedAt?:string;lastTriggerAt?:string;nextTriggerAt?:string;lastLabel?:string;lastStatus?:"triggered"|"completed"|"skipped_lock"|"no_targets"|"error";lastJobId?:string;lastMessage?:string;cycles:number;skippedDueToLock:number;providerNoTarget:number;};
const JOB_TTL=60*60*24*7;const memoryJobs=new Map<string,JobState>();const memoryLogs=new Map<string,string[]>();const memoryLatestByType=new Map<string,string>();const memoryActiveByType=new Map<string,string>();const LOG_CAP=200;const AUTO_PIPELINE_SCHEDULER_KEY="apex:autopipeline:scheduler";function jk(id:string){return`apex:job:${id}`;}function lk(id:string){return`apex:job:${id}:log`;}
export async function createJob(type:string):Promise<string>{const jobId=randomUUID();const state:JobState={jobId,type,status:"queued",progress:0,inserted:0,skipped:0,errors:0,total:0,startedAt:new Date().toISOString(),message:"Queued"};memoryJobs.set(jobId,{...state});memoryLatestByType.set(type,jobId);const wrote=await safeRedis(async rc=>{await rc.hset(jk(jobId),state as any);await rc.expire(jk(jobId),JOB_TTL);await rc.set(`apex:latestjob:${type}`,jobId,"EX",JOB_TTL);return true;},false);if(!wrote)logger.warn({jobId,type},"createJob: permanent Redis unavailable — using in-memory job state");return jobId;}
export async function updateJob(jobId:string,patch:Partial<JobState>):Promise<void>{const prev=memoryJobs.get(jobId);if(prev)memoryJobs.set(jobId,{...prev,...patch});else if(patch.jobId||patch.type)memoryJobs.set(jobId,{jobId,type:String(patch.type??"unknown"),status:(patch.status as JobStatus)??"running",progress:Number(patch.progress??0),inserted:Number(patch.inserted??0),skipped:Number(patch.skipped??0),errors:Number(patch.errors??0),total:Number(patch.total??0),startedAt:String(patch.startedAt??new Date().toISOString()),message:String(patch.message??""),...patch}as JobState);const flat:Record<string,string>={};for(const[k,v]of Object.entries(patch))if(v!==undefined)flat[k]=String(v);await safeRedis(rc=>rc.hset(jk(jobId),flat),undefined);}
export async function clearJobFields(jobId:string,fields:string[]):Promise<void>{if(!fields.length)return;await safeRedis(async rc=>{await rc.hdel(jk(jobId),...fields);await rc.expire(jk(jobId),JOB_TTL);},undefined);}
export async function appendJobLog(jobId:string,line:string,opts?:{dedupeKey?:string}):Promise<void>{if(opts?.dedupeKey){const ok=await safeRedis(async rc=>{const set=await rc.set(`apex:joblog:dedupe:${jobId}:${opts.dedupeKey}`,"1","EX",86400,"NX");return set==="OK"||set===true;},true);if(!ok)return;}const memCheck=memoryLogs.get(jobId)??[];if(memCheck[0]&&memCheck[0].includes(line.slice(0,120)))return;const ts=`${new Date().toISOString()} ${line}`;const mem=memoryLogs.get(jobId)??[];mem.unshift(ts);memoryLogs.set(jobId,mem.slice(0,LOG_CAP));await safeRedis(async rc=>{await rc.lpush(lk(jobId),ts);await rc.ltrim(lk(jobId),0,LOG_CAP-1);await rc.expire(lk(jobId),JOB_TTL);},undefined);void import("./bureau-live-log").then(m=>m.mirrorJobLogLine(jobId,line)).catch(()=>undefined);}
export async function getJob(jobId:string):Promise<JobState|null>{let redisOk=false;const raw=await safeRedis(async rc=>{redisOk=true;return rc.hgetall(jk(jobId));},null);if(!redisOk)return null;if(!raw||Object.keys(raw).length===0)return memoryJobs.get(jobId)??null;return{jobId:raw.jobId??jobId,type:raw.type??"unknown",status:(raw.status??"queued")as JobStatus,progress:Number(raw.progress??0),inserted:Number(raw.inserted??0),skipped:Number(raw.skipped??0),errors:Number(raw.errors??0),total:Number(raw.total??0),startedAt:raw.startedAt??"",finishedAt:raw.finishedAt,message:raw.message??"",atlasPhase:raw.atlasPhase!==undefined?Number(raw.atlasPhase):undefined,atlasPhaseTotal:raw.atlasPhaseTotal!==undefined?Number(raw.atlasPhaseTotal):undefined,entityProgress:raw.entityProgress!==undefined?Number(raw.entityProgress):undefined,entityTotal:raw.entityTotal!==undefined?Number(raw.entityTotal):undefined,entityNames:raw.entityNames,atlasTelemetry:raw.atlasTelemetry,outcome:raw.outcome==="incomplete"||raw.outcome==="complete"?raw.outcome:undefined,resumable:raw.resumable,targetIds:raw.targetIds,targetIndex:raw.targetIndex!==undefined?Number(raw.targetIndex):undefined,targetTotal:raw.targetTotal!==undefined?Number(raw.targetTotal):undefined,currentTargetId:raw.currentTargetId!==undefined?Number(raw.currentTargetId):undefined,currentPhase:raw.currentPhase,completedTargetIds:raw.completedTargetIds,failedTargetIds:raw.failedTargetIds,retryCounts:raw.retryCounts,result:raw.result};}
export async function getJobLog(jobId:string):Promise<string[]>{const r=await safeRedis(rc=>rc.lrange(lk(jobId),0,LOG_CAP-1),null as string[]|null);return r&&r.length?r:memoryLogs.get(jobId)??[];}
const DEDUP_KEY="apex:dedup:hnwi";export async function isDuplicate(k:string){return permSismember(DEDUP_KEY,k);}export async function markSeen(k:string){await permSadd(DEDUP_KEY,k);}export async function getDedupCount(){return permScard(DEDUP_KEY);}export async function clearDedup(){const k=`apex:${DEDUP_KEY}`;await withPermanentClient(async rc=>{await rc.del(k);logger.info({key:k},"Dedup set cleared");},undefined);}export async function preloadDedupPrefix(prefix:string){const seen=new Set<string>();await withPermanentClient(async rc=>{const k=`apex:${DEDUP_KEY}`;let c="0";do{const[n,m]=await rc.sscan(k,c,"MATCH",`${prefix}*`,`COUNT`,2000);c=n;for(const x of m)seen.add(x);}while(c!=="0");logger.info({prefix,count:seen.size},"Dedup prefix pre-loaded");},undefined);return seen;}export async function batchMarkSeen(keys:string[]){if(!keys.length)return;await withPermanentClient(rc=>rc.sadd(`apex:${DEDUP_KEY}`,...keys),undefined);}
const ACTIVE_JOB_READ_CACHE=new Map<string,{at:number;id:string|null}>();const ACTIVE_JOB_READ_TTL_MS=8000;
export async function setActiveJob(type:string,jobId:string):Promise<boolean>{if(!type||!jobId)throw new Error("Active job type and jobId are required");const result=await safeRedis(async rc=>Number(await rc.eval("local k=KEYS[1]; local current=redis.call('get',k); if current and current~=ARGV[1] then return 0 end; redis.call('set',k,ARGV[1],'EX',ARGV[2]); return 1",1,`apex:activejob:${type}`,jobId,String(JOB_TTL)))===1,null as boolean|null);if(result!==true)throw new Error(`Cannot claim active job lane '${type}': permanent Redis lock service unavailable or lane already owned`);memoryActiveByType.set(type,jobId);memoryLatestByType.set(type,jobId);ACTIVE_JOB_READ_CACHE.set(type,{at:Date.now(),id:jobId});return true;}
export async function getActiveJob(type:string){const c=ACTIVE_JOB_READ_CACHE.get(type);if(c&&Date.now()-c.at<ACTIVE_JOB_READ_TTL_MS)return c.id;let ok=false;const r=await safeRedis(async rc=>{ok=true;return rc.get(`apex:activejob:${type}`);},null as string|null);if(r){memoryActiveByType.set(type,r);ACTIVE_JOB_READ_CACHE.set(type,{at:Date.now(),id:r});return r;}if(ok){memoryActiveByType.delete(type);ACTIVE_JOB_READ_CACHE.set(type,{at:Date.now(),id:null});return null;}ACTIVE_JOB_READ_CACHE.delete(type);return null;}
export async function getActiveJobs(types:string[]){const out=new Map<string,string|null>();const ts=[...new Set(types)].filter(Boolean);if(!ts.length)return out;const now=Date.now();if(ts.every(t=>{const c=ACTIVE_JOB_READ_CACHE.get(t);if(!c||now-c.at>=ACTIVE_JOB_READ_TTL_MS)return false;out.set(t,c.id);return true;}))return out;let ok=false;const vals=await safeRedis(async rc=>{ok=true;return rc.mget(...ts.map(t=>`apex:activejob:${t}`));},null as Array<string|null>|null);if(!ok)return new Map(ts.map(t=>[t,null]));ts.forEach((t,i)=>{const id=vals?.[i]??null;out.set(t,id);if(id)memoryActiveByType.set(t,id);else memoryActiveByType.delete(t);ACTIVE_JOB_READ_CACHE.set(t,{at:now,id});});return out;}
export function invalidateActiveJobCache(type?:string){if(type)ACTIVE_JOB_READ_CACHE.delete(type);else ACTIVE_JOB_READ_CACHE.clear();}
export async function getLatestJob(type:string){let ok=false;const r=await safeRedis(async rc=>{ok=true;const id=await rc.get(`apex:latestjob:${type}`);return id?getJob(id):null;},null);if(!ok)return null;return r;}
export async function updateAutoPipelineScheduler(patch:Partial<AutoPipelineSchedulerStatus>){const flat:Record<string,string>={};for(const[k,v]of Object.entries(patch))if(v!==undefined)flat[k]=String(v);if(!Object.keys(flat).length)return;await safeRedis(async rc=>{await rc.hset(AUTO_PIPELINE_SCHEDULER_KEY,flat);await rc.expire(AUTO_PIPELINE_SCHEDULER_KEY,JOB_TTL);},undefined);}
export async function getAutoPipelineScheduler(){const r=await safeRedis(rc=>rc.hgetall(AUTO_PIPELINE_SCHEDULER_KEY),{});return{enabled:r.enabled==="true",active:r.active==="true",activatedAt:r.activatedAt,lastTriggerAt:r.lastTriggerAt,nextTriggerAt:r.nextTriggerAt,lastLabel:r.lastLabel,lastStatus:["triggered","completed","skipped_lock","no_targets","error"].includes(r.lastStatus??"")?r.lastStatus as AutoPipelineSchedulerStatus["lastStatus"]:undefined,lastJobId:r.lastJobId,lastMessage:r.lastMessage,cycles:Number(r.cycles??0),skippedDueToLock:Number(r.skippedDueToLock??0),providerNoTarget:Number(r.providerNoTarget??0)};}
export async function clearActiveJob(type:string){const result=await safeRedis(async rc=>Number(await rc.eval("local k=KEYS[1]; local id=redis.call('get',k); if not id then return 0 end; local s=redis.call('hget',ARGV[1]..id,'status'); if s=='done' or s=='failed' or s=='cancelled' then redis.call('del',k); return 1 end; return 0",1,`apex:activejob:${type}`,"apex:job:"))===1,null as boolean|null);if(result!==true)throw new Error(`Cannot clear active job lane '${type}': distributed lock service unavailable or job is still active`);invalidateActiveJobCache(type);memoryActiveByType.delete(type);return true;}
export async function forceClearActiveJob(type:string){return clearActiveJob(type);}
export async function clearActiveJobIfMatches(type:string,jobId:string):Promise<boolean>{invalidateActiveJobCache(type);let ok=false;const outcome=await safeRedis(async rc=>{ok=true;return Number(await rc.eval("if redis.call('get', KEYS[1]) == ARGV[1] then return redis.call('del', KEYS[1]) else return 0 end",1,`apex:activejob:${type}`,jobId))===1;},null as boolean|null);if(!ok)return false;if(outcome){memoryActiveByType.delete(type);ACTIVE_JOB_READ_CACHE.set(type,{at:Date.now(),id:null});}return outcome;}
export async function ownsActiveJob(type:string,jobId:string){return(await getActiveJob(type))===jobId;}
export async function clearActiveJobIfOwned(type:string,jobId:string){return clearActiveJobIfMatches(type,jobId);}
