import { Router, type IRouter } from "express";
import healthRouter from "./health";
import entitiesRouter from "./entities";
import safeEntityMergeRouter from "./entity-merge-safe";
import assetsRouter from "./assets";
import relationshipsRouter from "./relationships";
import researchRouter from "./research";
import dashboardRouter from "./dashboard";
import graphRouter from "./graph";
import ingestRouter from "./ingest";
import searchRouter from "./search";
import improveRouter from "./improve";
import osintToolsRouter from "./osint-tools";
import identityRouter from "./identity";
import contactResearchRouter from "./contact-research";
import canonicalAtlasLaunchRouter from "./research/canonical-atlas-launch";
import { atlasRouter } from "./atlas";
import bureauStreamRouter from "./bureau-stream";
import systemStatusRouter from "./system-status";
import investigatorTraceRouter from "./investigator-trace";
import { legacyApexMutationGuard } from "../lib/legacy-apex-mutation-guard";
import { entityVisibilityGuard } from "../lib/entity-visibility-guard";
import { legacyAtlasLaunchQuarantine } from "../lib/legacy-atlas-launch-quarantine";
import { normalizeAtlasLaunchBody } from "../middlewares/normalize-atlas-launch-body";
import { canonicalCaseContinuationGuard } from "../middlewares/canonical-case-continuation-guard";
import operatorAuthRouter from "./operator-auth";
import { requireOperatorAuth } from "../lib/operator-auth";

const router: IRouter = Router();

// Auth bootstrap must be public, but every operational route (including detailed health) is behind the server-side boundary.
// Operator sign-in routes and public liveness precede the fail-closed guard.
router.use(operatorAuthRouter);
router.use(requireOperatorAuth);
router.use(healthRouter);
router.use(normalizeAtlasLaunchBody);
router.use(entityVisibilityGuard);
router.use(legacyApexMutationGuard);
router.use(safeEntityMergeRouter);
router.use(entitiesRouter);
router.use(assetsRouter);
router.use(relationshipsRouter);
router.use(canonicalCaseContinuationGuard);
router.use(researchRouter);
router.use(dashboardRouter);
router.use(graphRouter);
router.use(canonicalAtlasLaunchRouter);
router.use(ingestRouter);
router.use(searchRouter);
router.use(improveRouter);
router.use(osintToolsRouter);
router.use(identityRouter);
router.use(contactResearchRouter);
router.use(legacyAtlasLaunchQuarantine);
router.use(atlasRouter);
router.use(bureauStreamRouter);
router.use(systemStatusRouter);
router.use(investigatorTraceRouter);

export default router;
