import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import entitiesRouter from "./entities";
import safeEntityMergeRouter from "./entity-merge-safe";
import assetsRouter from "./assets";
import relationshipsRouter from "./relationships";
import researchRouter from "./research";
import dashboardRouter from "./dashboard";
import graphRouter from "./graph";
import ingestRouter from "./ingest";
import searchRouter from "./search";
import improveRouter from "./improve";
import osintToolsRouter from "./osint-tools";
import identityRouter from "./identity";
import contactResearchRouter from "./contact-research";
import canonicalAtlasLaunchRouter from "./research/canonical-atlas-launch";
import { atlasRouter } from "./atlas";
import bureauStreamRouter from "./bureau-stream";
import systemStatusRouter from "./system-status";
import investigatorTraceRouter from "./investigator-trace";
import { legacyApexMutationGuard } from "../lib/legacy-apex-mutation-guard";
import { entityVisibilityGuard } from "../lib/entity-visibility-guard";
import { legacyAtlasLaunchQuarantine } from "../lib/legacy-atlas-launch-quarantine";
import { normalizeAtlasLaunchBody } from "../middlewares/normalize-atlas-launch-body";

const router: IRouter = Router();
router.use(healthRouter);
router.use(authRouter);
router.use(normalizeAtlasLaunchBody);
router.use(entityVisibilityGuard);
router.use(legacyApexMutationGuard);
// Transactional merge must precede the historical entities router so the old
// non-atomic implementation cannot execute for any operator request.
router.use(safeEntityMergeRouter);
router.use(entitiesRouter);
router.use(assetsRouter);
router.use(relationshipsRouter);
router.use(researchRouter);
router.use(dashboardRouter);
router.use(graphRouter);
router.use(ingestRouter);
router.use(searchRouter);
router.use(improveRouter);
router.use(osintToolsRouter);
router.use(identityRouter);
router.use(contactResearchRouter);
router.use(canonicalAtlasLaunchRouter);
router.use(legacyAtlasLaunchQuarantine);
router.use(atlasRouter);
router.use(bureauStreamRouter);
router.use(systemStatusRouter);
router.use(investigatorTraceRouter);
export default router;
