// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/apex-dashboard/DashDesktop.tsx": () => import("../components/mockups/apex-dashboard/DashDesktop.tsx"),
  "./components/mockups/apex-dashboard/DashMobile.tsx": () => import("../components/mockups/apex-dashboard/DashMobile.tsx"),
  "./components/mockups/apex-ledger/LedgerMobile.tsx": () => import("../components/mockups/apex-ledger/LedgerMobile.tsx"),
  "./components/mockups/apex-manual/FieldManualXI.tsx": () => import("../components/mockups/apex-manual/FieldManualXI.tsx"),
  "./components/mockups/apex-nav/SidebarNav.tsx": () => import("../components/mockups/apex-nav/SidebarNav.tsx"),
  "./components/mockups/dashboard/DashDesktop.tsx": () => import("../components/mockups/dashboard/DashDesktop.tsx"),
  "./components/mockups/dashboard/DashMobile.tsx": () => import("../components/mockups/dashboard/DashMobile.tsx"),
  "./components/mockups/dashboard/DashTablet.tsx": () => import("../components/mockups/dashboard/DashTablet.tsx"),
  "./components/mockups/manual/ClassifiedDossier.tsx": () => import("../components/mockups/manual/ClassifiedDossier.tsx"),
  "./components/mockups/manual/MissionBriefing.tsx": () => import("../components/mockups/manual/MissionBriefing.tsx"),
  "./components/mockups/mobile-screens/Crm.tsx": () => import("../components/mockups/mobile-screens/Crm.tsx"),
  "./components/mockups/mobile-screens/Dashboard.tsx": () => import("../components/mockups/mobile-screens/Dashboard.tsx"),
  "./components/mockups/mobile-screens/Entities.tsx": () => import("../components/mockups/mobile-screens/Entities.tsx"),
  "./components/mockups/mobile-screens/Graph.tsx": () => import("../components/mockups/mobile-screens/Graph.tsx"),
  "./components/mockups/mobile-screens/Mcts.tsx": () => import("../components/mockups/mobile-screens/Mcts.tsx"),
  "./components/mockups/apex-profile/ProfileDesktop.tsx": () => import("../components/mockups/apex-profile/ProfileDesktop.tsx"),
  "./components/mockups/nav/BottomTabs.tsx": () => import("../components/mockups/nav/BottomTabs.tsx"),
  "./components/mockups/nav/CompactSidebar.tsx": () => import("../components/mockups/nav/CompactSidebar.tsx"),
  "./components/mockups/nav/Current.tsx": () => import("../components/mockups/nav/Current.tsx"),
  "./components/mockups/pages/DeepSearchMobile.tsx": () => import("../components/mockups/pages/DeepSearchMobile.tsx"),
  "./components/mockups/pages/ProfileMobile.tsx": () => import("../components/mockups/pages/ProfileMobile.tsx")
};
