// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/manual/ClassifiedDossier.tsx": () => import("../components/mockups/manual/ClassifiedDossier.tsx"),
  "./components/mockups/manual/MissionBriefing.tsx": () => import("../components/mockups/manual/MissionBriefing.tsx")
};
